### ISSUE TITLE
Text Index Support

### ISSUE THREAD

**Issue by eltimn** [sgrouples/rogue-fsqio#15]
I added [Text Index support](https://github.com/foursquare/rogue/commit/30dc45aadb545e7ebb3645db23a8bc0f14deb1e4) to 4sq's v2 branch, but it never made it to the v3 branch or the subsequent move to the monorepo, or your fork.

Would you be interested in a PR for that? I'd like to get off this custom build I have of Rogue.

I'm glad you guys forked it because I've been thinking about doing the same thing for a couple of years. Looking forward to checking out your work on case classes, too.

**Comment by marekzebrowski** [comment]
If you can open PR against our repo we will happily merge it.

**Comment by eltimn** [comment]
I didn't realize you were using your fork of LIft for this. Is that solely for the async support you added to lift-mongodb?

If so, would you be willing to send a PR to Lift for that? I went through the commits and the code looks good, the only thing I'd say is nowadays I prefer `JavaConverters` to `JavaConversions`, but other than that it's pretty much what I envisioned async support would look like.

**Comment by marekzebrowski** [comment]
Yes, our for was required for async support. That unfortunately required changes to lift mongo code to support driver version 3.x 
I asked question in lift group, but answer was that version 2.6 can't accept such breaking changes, so no progress was made in that area.

**Comment by eltimn** [comment]
That's right, we weren't able to upgrade the mongo-java-driver for v2.6 , but v3 was recently released and master is now using v3.4.0 of the mongo-java-driver.

**Comment by eltimn** [comment]
Here's the commit: https://github.com/lift/framework/commit/6de40043fbeddb107467e6b0b5518786768cec79
